// --- INFORMACIÓN DE LA PLACA Y ENTORNO ---
#define STRING_CONFIG_H_AUTHOR "LowRider v2 - BTT Octopus"
#define MOTHERBOARD BOARD_BTT_OCTOPUS_V1_1

// --- PUERTOS DE COMUNICACIÓN ---
#define SERIAL_PORT -1
#define BAUDRATE 250000
#define SERIAL_PORT_2 1

// --- CONFIGURACIÓN DE DRIVERS ---
// MTR0: X | MTR1: Y1 | MTR2: Y2 | MTR3: Z1 | MTR4: Z2
#define X_DRIVER_TYPE  TMC2209
#define Y_DRIVER_TYPE  TMC2209
#define Z_DRIVER_TYPE  TMC2209
#define X2_DRIVER_TYPE TMC2209
#define Y2_DRIVER_TYPE TMC2209
#define Z2_DRIVER_TYPE TMC2209

// --- DESACTIVAR EXTRUSOR ( MODO CNC ) ---
#define EXTRUDERS 0
#define PREVENT_COLD_EXTRUSION
#define NOZZLE_TO_PROBE_OFFSET { 0, 0, 0 }

// --- PASOS POR MILÍMETRO Y VELOCIDADES (Eje Z con varilla roscada T8, X/Y con poleas 16T) ---
#define DEFAULT_AXIS_STEPS_PER_UNIT   { 100, 100, 400 }
#define DEFAULT_MAX_FEEDRATE          { 50, 50, 15 }
#define DEFAULT_MAX_ACCELERATION      { 180, 180, 80 }

// --- ENDSTOPS (FINALES DE CARRERA) ---
#define USE_XMIN_PLUG
#define USE_YMIN_PLUG
#define USE_ZMIN_PLUG
#define USE_YMAX_PLUG
#define USE_ZMAX_PLUG

#define X_HOME_DIR -1
#define Y_HOME_DIR -1
#define Z_HOME_DIR -1
